### ISSUE TITLE
[luci-interpreter] release build error

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#3310]
From https://github.com/Samsung/ONE/issues/457#issuecomment-661565390

> 11:12:20 /home/jenkins_slave/workspace/nnfw/master/push-nncc-release/compiler/luci-interpreter/src/kernels/SpaceToDepth.h:35:31: error: 'std::vector<const luci_interpreter::Tensor*> luci_interpreter::kernels::SpaceToDepth::getInputTensors() const' marked 'override', but does not override
11:12:20    std::vector<const Tensor *> getInputTensors() const override { return {_input}; }
11:12:20                                ^~~~~~~~~~~~~~~
11:12:20 /home/jenkins_slave/workspace/nnfw/master/push-nncc-release/compiler/luci-interpreter/src/kernels/SpaceToDepth.h:36:25: error: 'std::vector<luci_interpreter::Tensor*> luci_interpreter::kernels::SpaceToDepth::getOutputTensors() const' marked 'override', but does not override
11:12:20    std::vector<Tensor *> getOutputTensors() const override { return {_output}; }
11:12:20                          ^~~~~~~~~~~~~~~~

> 11:12:22 /home/jenkins_slave/workspace/nnfw/master/push-nncc-release/compiler/luci-interpreter/src/kernels/SpaceToDepth.cpp:27:82: error: no matching function for call to 'luci_interpreter::KernelWithParams<luci_interpreter::SpaceToDepthParams>::KernelWithParams(const luci_interpreter::SpaceToDepthParams&)'
11:12:22      : KernelWithParams<SpaceToDepthParams>(params), _input(input), _output(output)
11:12:22                                                                                   ^
11:12:22 In file included from /home/jenkins_slave/workspace/nnfw/master/push-nncc-release/compiler/luci-interpreter/src/kernels/SpaceToDepth.h:20:0,

**Comment by jinevening** [comment]
It seems that #3291 and #3230 make conflicts. Reverting #3230 may solve the issue. @struss, can you upload the PR with the changed interface?

**Comment by seanshpark** [comment]
fixed
