### ISSUE TITLE
[circle-mlir] Check build on Ubuntu 24.04

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#15215]
Let's check building on Ubuntu 24.04 of circle-mlir.

**Comment by seanshpark** [comment]
## Build Issues (WIP)

`make overlay`
- h5py builds from source
  - requires `pkg-config` Debian package
  - `libhdf5.so` not found -> requires `libhdf5-dev` Debian package
  - `module 'pkgutil' has no attribute 'ImpImporter'` -> ?

`make prep`
- abseil: gcc-13 drops error

**Comment by seanshpark** [comment]
## Upgrade abseil or can we drop ?

`abseil-cpp` is used codes from TensorFlow.

in `circle-mlir/circle-mlir/lib/dialect/utils/Padding.h`
> using StringPiece = absl::string_view;

in `circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp`
> std::string bytes_data = absl::HexStringToBytes(data.substr(2));

**Comment by seanshpark** [comment]
update abseil to "d9e4955c65cd4367dd6bf46f4ccb8cd3d100540b" # 20250127.1

-> error
> CircleExport.cpp:711:27: error: ‘StrCat’ is not a member of ‘absl’

-> add `#include <absl/strings/str_cat.h>`

**Comment by seanshpark** [comment]
## circle-mlur build check

`circle-mlir/circle-mlir/lib/arser/include/arser/arser.h` needs 
`#include <cstdint>`

**Comment by seanshpark** [comment]
Test is OK with built binaries.

**Comment by seanshpark** [comment]
done
