### ISSUE TITLE
[compiler] Check build on Ubuntu 24.04

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#15220]
Let's check compiler modules build check on Ubuntu 24.04

**Comment by seanshpark** [comment]
```
compiler/mir/include/mir/ShapeRange.h:29:17: error: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Werror=deprecated-declarations]
   29 |   : public std::iterator<std::forward_iterator_tag, Index, std::size_t, Index *, Index &>
      |                 ^~~~~~~~
```

**Comment by seanshpark** [comment]
```
mir/include/mir/Attributes.h:31:20: error: ‘int32_t’ is not a member of ‘std’; did you mean ‘int32_t’?
```

**Comment by seanshpark** [comment]
```
coco/core/include/coco/IR/Op.h:54:11: error: ‘uint32_t’ does not name a type
```

**Comment by seanshpark** [comment]
```
nnc/backends/soft_backend/SBSerializer.cpp:18:
mir/include/mir/ShapeRange.h:29:17: error: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Werror=deprecated-declarations]
   29 |   : public std::iterator<std::forward_iterator_tag, Index, std::size_t, Index *, Index &>
      |                 ^~~~~~~~
```

**Comment by seanshpark** [comment]
```
nnc/include/support/CommandLine.h:472:30: error: ‘uint64_t’ was not declared in this scope
```

**Comment by seanshpark** [comment]
```
moco/import/src/Nodes/Const.cpp:147:15: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  147 |   const auto &input_tensor = plier::tf::get_tensor_attr(node, "value");
      |               ^~~~~~~~~~~~
```

**Comment by seanshpark** [comment]
```
nnkit/actions/HDF5/Common.h:53:28: error: ‘uint32_t’ was not declared in this scope
```

**Comment by seanshpark** [comment]
```
-- Configure DALGONA
-- Build dalgona: FALSE (Python version 3.12 or higher is not supported yet)
-- Configure DALGONA - Done
```

**Comment by seanshpark** [comment]
```
compiler/logo-core/include/logo/Pass.h:41:16: error: ‘virtual bool logo::Pass::run(loco::Graph*)’ was hidden [-Werror=overloaded-virtual=]
   41 |   virtual bool run(loco::Graph *graph) = 0;
      |                ^~~
```

**Comment by seanshpark** [comment]
```
compiler/luci/pass/src/VerifyQuantizedNodeType.h:140:8: error: ‘bool luci::VerifyQuantizedNodeTypeBase<Qtype, Btype>::visit(const luci::CircleN
ode*) [with loco::DataType Qtype = loco::DataType::U8; loco::DataType Btype = loco::DataType::S32]’ was hidden [-Werror=overloaded-virtual=]
  140 |   bool visit(const luci::CircleNode *) { return true; }
      |        ^~~~~
```

**Comment by seanshpark** [comment]
```
luci-interpreter/src/kernels/GRU.cpp:77:10: error: ‘void operator delete(void*, std::size_t)’ called on pointer returned from a mismatched allocation function [-Werror=mismatched-new-delete]
   77 |   delete output_hidden_data;
      |          ^~~~~~~~~~~~~~~~~~
```

**Comment by seanshpark** [comment]
check done

**Comment by seanshpark** [comment]
done
